version:  '3.9'

services:

  wordpress:
    image: local
    container_name: wordpress
    build:
      context: wordpress/
      dockerfile: Dockerfile
    env_file:
      - inception.env
    restart: always
    ports:
      - 9000:80
    volumes:
      - ./wordpress/volumes:/var/www/html
    networks:
      inception:
        aliases: 
          - wp

  web:
    image: nginx
    container_name: nginx
    build:
      context: nginx/
      dockerfile: Dockerfile
    volumes:
      - ./wordpress/volumes:/var/www/html
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
  redis:
    image: redis
    container_name: redis
    build:
      context: bonus/redis/
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    networks:
      inception:
        aliases: 
          - redis
    restart: always

  ftp:
    image: ftp
    container_name: ftp
    build:
      context: bonus/ftp/
      dockerfile: Dockerfile
    env_file:
      - inception.env
    volumes:
      - ./wordpress/volumes:/home/wp_user/
    ports:
      - 21:21
      - 21000-21010:21000-21010
    networks:
      inception:
        aliases: 
          - ftp
    restart: always

  db:
    image: mariadb
    container_name: mariadb
    build:
      context: 'mariadb/'
      dockerfile: Dockerfile
    env_file:
      - inception.env
    ports:
      - "3306:3306"
    volumes:
      - /Users/bclerc/inception/mariadb/data:/var/lib/mysql
    restart: always
    networks:
      inception:
        aliases:
          - db

networks:
  inception:
    driver: bridge